package apache.cayenne.mappings.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import apache.cayenne.mappings.Subtheme;

/**
 * Class _Theme was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Theme extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PRIMARY_KEY_PK_COLUMN = "primaryKey";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Subtheme>> SUBTHEMES = Property.create("subthemes", List.class);

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToSubthemes(Subtheme obj) {
        addToManyTarget("subthemes", obj, true);
    }
    public void removeFromSubthemes(Subtheme obj) {
        removeToManyTarget("subthemes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Subtheme> getSubthemes() {
        return (List<Subtheme>)readProperty("subthemes");
    }


}
