package apache.cayenne.mappings.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import apache.cayenne.mappings.Role;
import apache.cayenne.mappings.Solution;
import apache.cayenne.mappings.Task;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PRIMARY_KEY_PK_COLUMN = "primaryKey";

    public static final Property<String> FIRST_NAME = Property.create("firstName", String.class);
    public static final Property<String> LAST_NAME = Property.create("lastName", String.class);
    public static final Property<String> LOGIN = Property.create("login", String.class);
    public static final Property<String> MIDDLE_NAME = Property.create("middleName", String.class);
    public static final Property<String> PASSWORD = Property.create("password", String.class);
    public static final Property<Double> RATING = Property.create("rating", Double.class);
    public static final Property<Integer> ROLE = Property.create("role", Integer.class);
    public static final Property<Role> ROLE1 = Property.create("role1", Role.class);
    public static final Property<List<Solution>> SOLUTIONS = Property.create("solutions", List.class);
    public static final Property<List<Task>> TASKS = Property.create("tasks", List.class);

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setLogin(String login) {
        writeProperty("login", login);
    }
    public String getLogin() {
        return (String)readProperty("login");
    }

    public void setMiddleName(String middleName) {
        writeProperty("middleName", middleName);
    }
    public String getMiddleName() {
        return (String)readProperty("middleName");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setRating(Double rating) {
        writeProperty("rating", rating);
    }
    public Double getRating() {
        return (Double)readProperty("rating");
    }

    public void setRole(Integer role) {
        writeProperty("role", role);
    }
    public Integer getRole() {
        return (Integer)readProperty("role");
    }

    public void setRole1(Role role1) {
        setToOneTarget("role1", role1, true);
    }

    public Role getRole1() {
        return (Role)readProperty("role1");
    }


    public void addToSolutions(Solution obj) {
        addToManyTarget("solutions", obj, true);
    }
    public void removeFromSolutions(Solution obj) {
        removeToManyTarget("solutions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Solution> getSolutions() {
        return (List<Solution>)readProperty("solutions");
    }


    public void addToTasks(Task obj) {
        addToManyTarget("tasks", obj, true);
    }
    public void removeFromTasks(Task obj) {
        removeToManyTarget("tasks", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Task> getTasks() {
        return (List<Task>)readProperty("tasks");
    }


}
